---

    - name: NGINX | Install NGINX
      apt: name=nginx state=latest update_cache=true

    - name: NGINX | Starting NGINX
      service:
        name: nginx
        state: started

    - name: NGINX | Setup NGINX conf
      copy: src={{playbook_dir}}/default.conf dest=/etc/nginx/conf.d/default.conf 
      notify: restart nginx

