---

    - name: JENKINS | Install libs
      raw: pip install python-jenkins lxml

    - name: JENKINS | Create Jenkins job
      jenkins_job:
         config: "{{ lookup('file', '{{playbook_dir}}/test.xml') }}"
         name: test
         password: f42e958af9774970b4d5eb4a071cabb1
         url: http://localhost:49001
         user: admin


